name: PHP Tests and CS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction
        working-directory: ./Website/htdocs/mpmanager

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        working-directory: ./Website/htdocs/mpmanager

      - name: PhpCS
        run: composer phpcs
        working-directory: ./Website/htdocs/mpmanager

